on:
  push:
    tags:
      - "v*"

name: Release

jobs:
  release:
    name: Release
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      matrix:
        cfg:
          - { os: windows-latest, build: win64, build-update: true }
          - { os: macos-latest, build: mac }
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Build
        run: yarn build:${{ matrix.cfg.build }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/Arknights Gacha Export-*.zip
          draft: false
          prerelease: false
      - name: Build update
        if: matrix.cfg.build-update
        run: yarn build-update
      - name: Deploy update
        if: matrix.cfg.build-update
        uses: crazy-max/ghaction-github-pages@v2
        with:
          commit_message: Update app
          build_dir: build/update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
